### ISSUE TITLE
ValueError: cannot reshape array of size 14930496 into shape (4976832,)

### ISSUE THREAD

**Issue by flora992** [thiagosantos1/CNN_Find_Glasses#1]
hi, this error happened on line 216 in cnn_glasses.py. I was predicting a JPG using your model. 
```
Traceback (most recent call last):
  File "cnn_glasses.py", line 294, in <module>
    prediction = model.single_test(img)
  File "cnn_glasses.py", line 216, in single_test
    pred = self.sess.run(self.y_conv, feed_dict={self.x: [img.reshape(width*height)], self.keep_prob: 1.0})
ValueError: cannot reshape array of size 14930496 into shape (4976832,)
```

**Comment by atomicsyed-99** [comment]
> hi, this error happened on line 216 in cnn_glasses.py. I was predicting a JPG using your model.
> 
> ```
> Traceback (most recent call last):
>   File "cnn_glasses.py", line 294, in <module>
>     prediction = model.single_test(img)
>   File "cnn_glasses.py", line 216, in single_test
>     pred = self.sess.run(self.y_conv, feed_dict={self.x: [img.reshape(width*height)], self.keep_prob: 1.0})
> ValueError: cannot reshape array of size 14930496 into shape (4976832,)
> ```

Hey , did you find the solution to this? Please help me out if you did so!

**Comment by rleaver152** [comment]
You need to resize and convert your image files to 112x112 in Y (out of YUV) colourspace.  

This will do it (using ImageMagick)

for file in *.jpg ; do \
convert "$file" -resize 112x112 -extent 112x112 -separate newimage_"$RANDOM"_%d.jpg ; 
done


You only need the first channel of each converted file.   I think the output conversion format has to be jpg/jpeg to ensure YUV and not RGB format.  I'm being lazy in writing the outputs here by using a random string to avoid overwriting my results :-)

I'm resizing to those parameters simply to match the examples the author provided.
